### PR TITLE
Bump runtime to 42

### PR DESCRIPTION
**Pull request by bbhtt**
PIng @cassidyjames, please review when you have time, thanks!

### CODE REVIEW

**Comment by hfiguiere** [comment]
libhandy is in the runtime now.

**Comment by bilelmoussaoui** [comment]
granite/icons/stylesheet are also in the baseapp, i would test a build without that

**Comment by hfiguiere** [comment]
> libhandy is in the runtime now.

and it fail to build because -Werror.

**Comment by bbhtt** [comment]
> libhandy is in the runtime now.

Thanks!

> granite/icons/stylesheet are also in the baseapp, i would test a build without that

It seems to require newer granite than what is available on the baseapp:

```
Dependency granite found: NO found 5.5.0 but need: '>= 6.0'
Found CMake: /usr/bin/cmake (3.23.2)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency granite found: NO (tried cmake)

../meson.build:17:0: ERROR: Invalid version of dependency, need 'granite' ['>= 6.0'] found '5.5.0'.
```

And the commit used for stylesheet is also newer than what is included in the baseapp, didn't check if that's required.

**Comment by bbhtt** [comment]
> Started [test build 101797](https://buildbot.flathub.org/#/builders/32/builds/101797)

It's "stuck" on validating appdata.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> And the commit used for stylesheet is also newer than what is included in the baseapp, didn't check if that's required.

Yea, I think it is needed. At least on first launch I can see that the stylesheet from the baseapp probably breaks the headerbar colouring;



From this

> Build [101952 successful](https://buildbot.flathub.org/#/builders/32/builds/101952) 

it looks correct:

**Pull request merged**
